openapi: 3.0.0
paths:
  /v1/colonias/por-id:
    get:
      operationId: ColoniasController_getByIds_v1
      parameters:
        - name: page
          required: false
          in: query
          description: Número de página que se desea obtener
          schema:
            minimum: 1
            default: 1
            type: number
        - name: limit
          required: false
          in: query
          description: Número de resultados por página
          schema:
            minimum: 1
            maximum: 100
            default: 10
            type: number
        - name: cve_ent
          required: true
          in: query
          description: Clave de la entidad federativa (2 dígitos)
          schema:
            example: "01"
            type: string
        - name: cve_mun
          required: true
          in: query
          description: Clave del municipio (3 dígitos)
          schema:
            example: "002"
            type: string
        - name: cve_loc
          required: true
          in: query
          description: Clave de la localidad (4 dígitos)
          schema:
            example: "0001"
            type: string
        - name: x-cloud-trace-context
          required: true
          in: header
          schema:
            type: string
      responses:
        "200":
          description: Búsqueda exitosa. Devuelve un arreglo de localidades.
        "204":
          description: Búsqueda exitosa pero sin resultados.
        "400":
          description: Parámetros de consulta inválidos.
      summary: Obtiene una o más colonias por sus claves geoestadísticas.
      tags: &a1
        - Cartografía
  /v1/colonias/por-coordenadas:
    get:
      operationId: ColoniasController_getByCoords_v1
      parameters:
        - name: page
          required: false
          in: query
          description: Número de página que se desea obtener
          schema:
            minimum: 1
            default: 1
            type: number
        - name: limit
          required: false
          in: query
          description: Número de resultados por página
          schema:
            minimum: 1
            maximum: 100
            default: 10
            type: number
        - name: lat
          required: true
          in: query
          schema:
            example: 21.880449
            type: number
        - name: lng
          required: true
          in: query
          schema:
            example: -102.296179
            type: number
        - name: radio
          required: false
          in: query
          description: Radio de búsqueda en metros
          schema:
            default: 1000
            example: 1000
            type: number
        - name: x-cloud-trace-context
          required: true
          in: header
          schema:
            type: string
      responses:
        "200":
          description: Búsqueda exitosa. Devuelve un arreglo de colonias.
        "204":
          description: Búsqueda exitosa pero sin resultados.
        "400":
          description: Parámetros de consulta inválidos (ej. lat/lng fuera de rango).
      summary: Busca colonias dentro de un radio a partir de coordenadas.
      tags: *a1
info:
  title: API Geoespaciales
  description: Conjunto de APIs con datos de cartografía, socioeconómicos, y más.
  version: "1.0"
  contact: {}
tags:
  - name: Cartografía
    description: ""
  - name: Indicadores Demográficos
    description: ""
  - name: Comercio
    description: ""
  - name: Vivienda
    description: ""
servers: []
components:
  schemas: {}
